/** Shared responsive layout class names for admin pages. See globals.css. */
export const adminLayout = {
  paneHeader: 'hof-admin-pane-header',
  paneTitle: 'hof-admin-pane-title',
  paneCta: 'hof-admin-pane-cta',
  section: 'hof-admin-section',
  padSection: 'hof-admin-pad-section',
  padSectionBottom: 'hof-admin-pad-section-bottom',
  kpiGrid: 'hof-admin-kpi-grid',
  twoCol: 'hof-admin-two-col',
  twoColEqual: 'hof-admin-two-col-equal',
  threeCol: 'hof-admin-three-col',
  fourCol: 'hof-admin-four-col',
  tableScroll: 'hof-admin-table-scroll',
  dataTable: 'hof-admin-data-table',
  dataTableLg: 'hof-admin-data-table hof-admin-data-table--lg',
  dataTableXl: 'hof-admin-data-table hof-admin-data-table--xl',
  cardHeader: 'hof-admin-card-header',
  widgetHeader: 'hof-admin-widget-header',
  searchBox: 'hof-admin-search-box',
  photoGrid: 'hof-admin-photo-grid',
  pagination: 'hof-admin-pagination',
  formTwoCol: 'hof-admin-form-two-col',
  filterGrid: 'hof-admin-filter-grid',
  modalGridThree: 'hof-admin-modal-grid-three',
} as const;
